version: "3.2"

services:
  ywd-panel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ywd-panel
    environment:
      - YWD_DATA_DIR=/data
    volumes:
      - ./data:/data
    ports:
      - 3002:3002
    restart: unless-stopped
